name: DEPLOYED_TO_DEV
on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
   if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Modify the status of JIRA TICKET to TO code review 
      uses: indiesdev/curl@v1.1
      id: update_ticket
      with:
        url: 'https://olive-soft.atlassian.net/rest/api/2/issue/${{ steps.extract.outputs.ticket_jira }}/transitions'
        method: 'POST'
        accept: 200,201,204
        basic-auth-token: ${{ secrets.JIRA_TOKEN }}
        log-response: true
        body : '{"transition": { "id": "6" } }'
